// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import {env} from "./src/config/env"
import { defineConfig } from "prisma/config";

if (!env.db_url) {
  throw new Error("DATABASE_URL is not configured.");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env.db_url,
  },
});
